name: test_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cudatoolkit=11.2.2=hbe64b41_10
  - cudnn=8.1.0.77=h90431f1_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.2=pyhff2d567_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.2=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - asteroid-filterbanks==0.4.0
    - attrs==24.3.0
    - audioread==3.0.1
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - ci-sdr==0.0.2
    - click==8.1.7
    - configargparse==1.7
    - contourpy==1.3.1
    - ctc-segmentation==1.7.4
    - cycler==0.12.1
    - cython==3.0.11
    - debugpy==1.6.7
    - distance==0.1.3
    - e==1.4.5
    - editdistance==0.8.1
    - einops==0.8.0
    - espnet==202402
    - espnet-model-zoo==0.1.7
    - espnet-tts-frontend==0.0.3
    - fast-bss-eval==0.1.3
    - fastjsonschema==2.21.1
    - filelock==3.15.4
    - fonttools==4.55.4
    - fsspec==2024.6.1
    - g2p-en==2.1.0
    - h5py==3.12.1
    - hear21passt==0.0.26
    - huggingface-hub==0.26.2
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - idna==3.10
    - importlib-metadata==4.13.0
    - inflect==7.0.0
    - jaconv==0.4.0
    - jamo==0.4.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kaldiio==2.18.0
    - kaleido==0.2.1
    - kiwisolver==1.4.8
    - librosa==0.9.2
    - llvmlite==0.43.0
    - markupsafe==2.1.5
    - matplotlib==3.10.0
    - mpmath==1.3.0
    - nbformat==5.10.4
    - networkx==3.3
    - nltk==3.9.1
    - noisereduce==3.0.3
    - numba==0.60.0
    - numpy==2.0.0
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - omegaconf==2.3.0
    - opencv-contrib-python==4.11.0.86
    - opencv-python==4.11.0.86
    - opt-einsum==3.4.0
    - pandas==2.2.3
    - pillow==11.0.0
    - pip==24.2
    - plotly==5.24.1
    - pooch==1.8.2
    - protobuf==3.20.3
    - psutil==5.9.0
    - pycparser==2.22
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pynndescent==0.5.13
    - pyparsing==3.2.1
    - pypinyin==0.44.0
    - pytz==2024.2
    - pyworld==0.3.4
    - pyyaml==6.0.2
    - pyzmq==25.1.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - resampy==0.4.3
    - rpds-py==0.22.3
    - s3prl==0.4.16
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentencepiece==0.1.97
    - setuptools==72.1.0
    - soundfile==0.12.1
    - sympy==1.13.1
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - timm==0.4.5
    - tokenizers==0.20.3
    - torch==2.5.1
    - torch-complex==0.4.4
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - tornado==6.1
    - tqdm==4.67.0
    - transformers==4.46.2
    - triton==3.1.0
    - typeguard==2.13.3
    - tzdata==2024.2
    - umap-learn==0.5.7
    - unidecode==1.3.8
    - urllib3==2.2.3
    - wheel==0.43.0
    - zipp==3.21.0
prefix: /home/suryasss/.conda/envs/test_gpu
